name: Build

# Rodado a cada push
on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: instala dependências
        run: npm install
      - name: cria build
        run: npm run build
